on:
  push

jobs:
  block-branch-name:
    name: ValidateBranchName
    runs-on: ubuntu-latest
    steps:
    - name: echo branch value
      run: echo "before SHA- ${{ GITHUB.SHA }}" "REF- ${{ GITHUB.REF }}"
    - uses: deepakputhraya/action-branch-name@master
      name: do branch validation
      with:
        regex: '([a-z])+\/([a-z])+' # Regex the branch should match. This example enforces grouping
        allowed_prefixes: 'feature,stable,fix' # All branches should start with the given prefix
        # ignore: master,develop # Ignore exactly matching branch names from convention
        # the easiest way to implement a banned list is to add them as
        # "ignores", and then delete on success
        ignore: master
        min_length: 5 # Min length of the branch name
        max_length: 20 # Max length of the branch name
    - name: echo branch value
      if: ${{ failure() }}
      run: echo "after SHA- ${{ GITHUB.SHA }}" "REF- ${{ GITHUB.REF }}"
    - name: DeleteBadBranch
      if: ${{ failure() }}
      run: |
        /bin/pwd
        ls -A .
        echo deleting ${{ github.ref }}
        git branch remove ${{ github.ref }}
